### ISSUE TITLE
Issue with the beforeDrop event

### ISSUE THREAD

**Issue by lliiuu** [jsplumb/jsplumb#933] opened 2020-05-22 07:49 UTC
I used the beforeDrop event on a jsPlumb instance to check whenever the connection can be made .  I used the return value of the beforeDrop event.

 I encountered the issue where if I dragged an already made connection to a invalid target endpoint (and the beforeDrop would return false), jsPlumb raises an internal error: `__jsPlumb function failed : TypeError: Cannot read property 'isDetachAllowed' of undefined`_.

**Comment by sporritt** [comment] 2020-05-23 12:24
are you able to provide a codepen or jsfiddle?

**Comment by lliiuu** [comment] 2020-05-25 02:59
Thank you for your answer, this is the key code。

`   ConnectionsDetachable: true,`

// beforeDrop
        _this.jsPlumb.bind("beforeDrop", function(evt) {
          console.log("beforeDrop", evt);
          let from = evt.sourceId;
          let to = evt.targetId;
          if (from === to) {
            return false;
          }
          if (_this.hasLine(from, to)) {
            return false;
          }
          if (_this.hashOppositeLine(from, to)) {
            return false;
          }
          return true;
        });``

> are you able to provide a codepen or jsfiddle?

**Comment by sporritt** [comment] 2020-05-25 07:59
are you able to provide a codepen or jsfiddle?

**Comment by lliiuu** [comment] 2020-05-25 09:07
> are you able to provide a codepen or jsfiddle?

[https://codepen.io/lliiuu/pen/VwvNaLJ](url)

**Comment by lliiuu** [comment] 2020-05-25 09:10
> are you able to provide a codepen or jsfiddle?

this is error screenshot。
![image](https://user-images.githubusercontent.com/21049382/82798083-a1899a00-9eaa-11ea-8cc1-a185c1ca1d51.png)

**Comment by sporritt** [comment] 2020-05-26 14:11
thanks.

i can't reproduce the issue in that fiddle though as there is no means to drag a new connection, and so given the beforeDrop:

```
_this.jsPlumb.bind("beforeDrop", function(evt) {
          console.log("beforeDrop", evt);
          let from = evt.sourceId;
          let to = evt.targetId;
          if (from === to) {
            _this.$message.error("不能连接自己");
            return false;
          }
          if (_this.hasLine(from, to)) {
            alert("Cannot duplicate connection");
            return false;
          }
          if (_this.hashOppositeLine(from, to)) {
            alert("No loopback");
            return false;
          }
          return true;
        });
```

..i can test by the first case, dragging a line back to the source node. but then your code throws an error `Cannot read property 'error' of undefined"`, which is because `this.$message` is undefined.

perhaps you could try setting a breakpoint yourself - you have the source to jsplumb.

**Comment by lliiuu** [comment] 2020-05-28 03:05
> thanks.
> 
> i can't reproduce the issue in that fiddle though as there is no means to drag a new connection, and so given the beforeDrop:
> 
> ```
> _this.jsPlumb.bind("beforeDrop", function(evt) {
>           console.log("beforeDrop", evt);
>           let from = evt.sourceId;
>           let to = evt.targetId;
>           if (from === to) {
>             _this.$message.error("不能连接自己");
>             return false;
>           }
>           if (_this.hasLine(from, to)) {
>             alert("Cannot duplicate connection");
>             return false;
>           }
>           if (_this.hashOppositeLine(from, to)) {
>             alert("No loopback");
>             return false;
>           }
>           return true;
>         });
> ```
> 
> ..i can test by the first case, dragging a line back to the source node. but then your code throws an error `Cannot read property 'error' of undefined"`, which is because `this.$message` is undefined.
> 
> perhaps you could try setting a breakpoint yourself - you have the source to jsplumb.

Thanks  Your patient answer。
 `Cannot read property 'error' of undefined"` have already been solved，Only dragging the source node to another node will cause problems，You can try to separate test1 to test2 and drag it to test3 to test2，The workbench will appear ` jsPlumb function failed : TypeError: Cannot read property 'isDetachAllowed' of undefined`。

**Comment by sporritt** [comment] 2020-05-28 13:35
sorry, i don't know what you mean. there isnt a way to drag new connections. detaching test1-test2 from test2 and dropping it on test3 doesnt result in a console error.

**Comment by sporritt** [comment] 2020-05-28 13:36
and you still do have the source, right?  i mean you could have put a breakpoint in the code by now and tracked it back. i know it's not your code etc but in the interests of expediency it might have been worth trying.

**Comment by lliiuu** [comment] 2020-05-29 02:45
thanks,this is screenshot
![image](https://user-images.githubusercontent.com/21049382/83215377-64b6ef00-a199-11ea-8f1e-7cbf116ecc85.png)
![image](https://user-images.githubusercontent.com/21049382/83215388-6aacd000-a199-11ea-830e-ba058bd1f4c5.png)
![image](https://user-images.githubusercontent.com/21049382/83215395-6e405700-a199-11ea-852f-a86e0f93ec5c.png)

**Comment by lliiuu** [comment] 2020-05-29 02:52
Thanks ! this is screenshot.
1.
![image](https://user-images.githubusercontent.com/21049382/83215777-53baad80-a19a-11ea-86e1-eedefd597b55.png)
2.
![image](https://user-images.githubusercontent.com/21049382/83215790-5b7a5200-a19a-11ea-989a-4e95636a3738.png)
3.
![image](https://user-images.githubusercontent.com/21049382/83215810-6339f680-a19a-11ea-91d6-58e1ef6ee063.png)

**Comment by sporritt** [comment] 2021-01-29 03:35
@lliiuu If this is still an issue for you I'd suggest the best course of action is to first switch to a 4.x release:

https://www.npmjs.com/package/@jsplumb/community

As far as possible, no further work on the 2.x branch is going to be undertaken, and in 4.x all of the code around drag/drop has been rewritten. Closing this issue. If something like this is still a problem for in 4.x please feel free to open a new issue.

**Closed by sporritt** 2021-01-29 03:35 UTC
