### ISSUE TITLE
Uncaught TypeError: Cannot create property 'scope' on number '1'

### ISSUE THREAD

**Issue by aawajjoshi** [jsplumb/jsplumb#929] opened 2020-04-28 02:36 UTC
Hello, 

Thank you for creating this amazing library. I am having a ton of fun playing around with it and learning new things. I am getting a reoccurring error which technically doesn't mess any of the functionalities. 
<img width="1440" alt="Screen Shot 2020-04-27 at 9 16 29 PM" src="https://user-images.githubusercontent.com/31771293/80439746-e383e800-88cc-11ea-8ab7-917ab004b858.png">

If I start out with a single connection and make any changes to it (as you can see, I have implemented connection color change and connection style change features) like in the above image, I don't come across any errors. 

However if I have two or more connections established and make any changes to them (see image below), I get the following error.
<img width="1440" alt="Screen Shot 2020-04-27 at 9 14 17 PM" src="https://user-images.githubusercontent.com/31771293/80439976-59884f00-88cd-11ea-9f23-a7c74994b7f0.png">
<img width="1438" alt="Screen Shot 2020-04-27 at 9 15 59 PM" src="https://user-images.githubusercontent.com/31771293/80440050-876d9380-88cd-11ea-928f-29adec5eb17b.png">
The issue - "Uncaught TypeError: Cannot create property 'scope' on number '1'"

Below is how I am making changes to connections (included snippet is for connection style change to Straight):

`
if (l.classList.contains("straight-line")) {
            defaultConnectionType = "Straight";

            let connected = jsPlumb.getConnections();
            $.each(connected, function (connection, e) {

                jsPlumb.select(connection).setConnector([defaultConnectionType]);

               //changing default connector style to influence any consequent connections
                jsPlumb.importDefaults({ Connector: [defaultConnectionType] });

                jsPlumb.repaintEverything();
            });
        }`

Please let me know if I can provide any additional information. Again, thank you.

**Comment by sporritt** [comment] 2020-04-28 08:16
Connector definitions can be either a string:

`"Straight"`

or an array with two elements:

`[ "Straight", { foo:"bar" } ]`

but you are passing in an array with one element:

`[ "Straight" ]`

I think that's probably the cause of the message you are seeing.

**Comment by sporritt** [comment] 2022-01-29 06:59
Closing this.  For future reference, this discussion relates to version 2.x, which is not unsupported. In 5.x, connector definitions can be either a string:

`"Straight"`

or an object in this form:

`{ type:"Straight", options:{ foo:"bar" } ]}`

**Closed by sporritt** 2022-01-29 06:59 UTC
