### ISSUE TITLE
Impossible to nest a group inside another

### ISSUE THREAD

**Issue by joccd** [jsplumb/jsPlumb#569] opened 2016-10-17 09:07 UTC
Hi,

Is it possible to nest a group inside another ? It works by code but not by drag/drop.

jsfiddle: https://jsfiddle.net/joccd/a4vm9cmw/

Regards,
Joccd

**Comment by sporritt** [comment] 2016-10-17 10:08
it only really works by accident. it was never the intention.

**Comment by sporritt** [comment] 2016-10-17 10:10
...in fact it is highly likely the code will be updated to prevent this from being supported.

**Comment by sporritt** [comment] 2016-10-17 10:12
(that fiddle doesnt do anything for me. what does it show?)

**Comment by joccd** [comment] 2016-10-17 10:16
It displays in the browser console the list of c1 children (when I drag/drop c2 in c1 I expected to get c2)

**Comment by sporritt** [comment] 2016-10-17 10:20
i see, but you dont, because nested groups are not supported.  if you manage to set this up programmatically you're not really nesting groups: if you were to collapse the parent group, connections to nodes that are its children would be collapsed. but no connections to children of the "nested" group would be collapsed.

**Comment by sporritt** [comment] 2016-10-28 22:16
closing this out. groups are not nestable by design.

**Closed by sporritt** 2016-10-28 22:16 UTC
