### ISSUE TITLE
Dragging connections in a scrollable div

### ISSUE THREAD

**Issue by mdinh7** [jsplumb/jsplumb#725] opened 2018-03-27 17:23 UTC
Currently I have two long lists that on rendered on the left and right side respectively. The div they are inside is scrollable using overflow. I configured making sources and targets on the list items using arrays and then iterating through them using makeSource and makeTarget. The problem occurs when I have to either drag from a top item on one side, to a very low item on the other side, which requires me to scroll. If I start to drag the connection, and then scroll, the connection itself will be left behind, and gets worse as I continue to scroll. This also happens when I try to drag from a source at the bottom and scroll up as well.  I noticed some of this behavior in the flowchart demo also. Is this something with the flowchart connector, or is it something with having a scrollable div? I noticed in most instances where it occurs, it is happening within a scrollable div, that is inside a greater page. I'm just looking for a solution that it will follow the cursor even when I scroll.

Thanks!

**Comment by Nasko-Kurtakov** [comment] 2018-07-19 14:07
I am also having the same issue. After some debbugging I noticed that the issue is due to the floating point coordinates being calculated using the pageX,pageY of the drag event. However when used in a scrolled div, those coordinaets are not right (as long as the document is not right). Meybe the calculations should take into consideration the scroll ofset of the plumb container instead of only the document scroll offset.

**Comment by sporritt** [comment] 2018-10-19 06:54
this issue is reputed to be fixed by the PR above, which was incorporated into release 2.8.1 of jsplumb today.

**Closed** 2019-06-05 19:16 UTC
